### ISSUE TITLE
Unable to parse plugin name from metadata in /var/www/discourse/plugins/discourse_user_auto_activation/plugin.rb

### ISSUE THREAD

**Issue by geekyouth** [angelim/discourse_user_auto_activation#2]
```

I, [2023-05-09T05:48:03.276587 #1]  INFO -- : > cd /var/www/discourse && su discourse -c 'bundle exec rake themes:update assets:precompile'
- Building
- Building
- cleaning up
- cleaning up
- cleaning up
Cannot read properties of undefined (reading 'cleanup')


Stack Trace and Error Report: /tmp/error.dump.57ae8cab726cbade9bb837726440d2b7.log
Unable to parse plugin name from metadata in /var/www/discourse/plugins/discourse_user_auto_activation/plugin.rb


Stack Trace and Error Report: /tmp/error.dump.77cae0b3b73b12bdf5958b601f5dbfee.log
error Command failed with exit code 1.
I, [2023-05-09T05:48:08.120374 #1]  INFO -- : yarn run v1.22.19
$ /var/www/discourse/app/assets/javascripts/node_modules/.bin/ember build -prod
Environment: production
cleaning up...
Cleanup error.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

app.yml
```
hooks:
  after_code:
    - exec:
        cd: $home/plugins
        cmd:
          - git clone https://github.com/discourse/docker_manager.git
          - git clone https://github.com/discourse/discourse-oauth2-basic.git
          - git clone https://github.com/discourse/discourse-openid-connect.git
          - git clone https://github.com/angelim/discourse_user_auto_activation.git
```
